package sonnicon.eonbot.type

enum EventType {
    GenericEvent,
    GenericUpdateEvent,
    RawGatewayEvent,
    GatewayPingEvent,

    ReadyEvent,
    ResumeEvent,
    ReconnectEvent,
    DisconnectEvent,
    ShutdownEvent,
    StatusChangeEvent,
    ExceptionEvent,

    UserUpdateNameEvent,
    UserUpdateDiscriminatorEvent,
    UserUpdateAvatarEvent,
    UserUpdateOnlineStatusEvent,
    UserUpdateActivityOrderEvent,
    UserTypingEvent,
    UserActivityStartEvent,
    UserActivityEndEvent,

    SelfUpdateAvatarEvent,
    SelfUpdateEmailEvent,
    SelfUpdateMFAEvent,
    SelfUpdateNameEvent,
    SelfUpdateVerifiedEvent,

    GuildMessageReceivedEvent,
    GuildMessageUpdateEvent,
    GuildMessageDeleteEvent,
    GuildMessageEmbedEvent,
    GuildMessageReactionAddEvent,
    GuildMessageReactionRemoveEvent,
    GuildMessageReactionRemoveAllEvent,

    PrivateMessageReceivedEvent,
    PrivateMessageUpdateEvent,
    PrivateMessageDeleteEvent,
    PrivateMessageEmbedEvent,
    PrivateMessageReactionAddEvent,
    PrivateMessageReactionRemoveEvent,

    MessageReceivedEvent,
    MessageUpdateEvent,
    MessageDeleteEvent,
    MessageBulkDeleteEvent,
    MessageEmbedEvent,
    MessageReactionAddEvent,
    MessageReactionRemoveEvent,
    MessageReactionRemoveAllEvent,

    StoreChannelDeleteEvent,
    StoreChannelUpdateNameEvent,
    StoreChannelUpdatePositionEvent,
    StoreChannelUpdatePermissionsEvent,
    StoreChannelCreateEvent,

    TextChannelDeleteEvent,
    TextChannelUpdateNameEvent,
    TextChannelUpdateTopicEvent,
    TextChannelUpdatePositionEvent,
    TextChannelUpdatePermissionsEvent,
    TextChannelUpdateNSFWEvent,
    TextChannelUpdateParentEvent,
    TextChannelUpdateSlowmodeEvent,
    TextChannelCreateEvent,

    VoiceChannelDeleteEvent,
    VoiceChannelUpdateNameEvent,
    VoiceChannelUpdatePositionEvent,
    VoiceChannelUpdateUserLimitEvent,
    VoiceChannelUpdateBitrateEvent,
    VoiceChannelUpdatePermissionsEvent,
    VoiceChannelUpdateParentEvent,
    VoiceChannelCreateEvent,

    CategoryDeleteEvent,
    CategoryUpdateNameEvent,
    CategoryUpdatePositionEvent,
    CategoryUpdatePermissionsEvent,
    CategoryCreateEvent,

    PrivateChannelCreateEvent,
    PrivateChannelDeleteEvent,

    GuildReadyEvent,
    GuildJoinEvent,
    GuildLeaveEvent,
    GuildAvailableEvent,
    GuildUnavailableEvent,
    UnavailableGuildJoinedEvent,
    UnavailableGuildLeaveEvent,
    GuildBanEvent,
    GuildUnbanEvent,

    GuildUpdateAfkChannelEvent,
    GuildUpdateSystemChannelEvent,
    GuildUpdateAfkTimeoutEvent,
    GuildUpdateExplicitContentLevelEvent,
    GuildUpdateIconEvent,
    GuildUpdateMFALevelEvent,
    GuildUpdateNameEvent,
    GuildUpdateNotificationLevelEvent,
    GuildUpdateOwnerEvent,
    GuildUpdateRegionEvent,
    GuildUpdateSplashEvent,
    GuildUpdateVerificationLevelEvent,
    GuildUpdateFeaturesEvent,
    GuildUpdateVanityCodeEvent,
    GuildUpdateBannerEvent,
    GuildUpdateDescriptionEvent,
    GuildUpdateBoostTierEvent,
    GuildUpdateBoostCountEvent,
    GuildUpdateMaxMembersEvent,
    GuildUpdateMaxPresencesEvent,

    GuildMemberJoinEvent,
    GuildMemberLeaveEvent,
    GuildMemberRoleAddEvent,
    GuildMemberRoleRemoveEvent,

    GuildMemberUpdateNicknameEvent,
    GuildMemberUpdateBoostTimeEvent,

    GuildVoiceUpdateEvent,
    GuildVoiceJoinEvent,
    GuildVoiceMoveEvent,
    GuildVoiceLeaveEvent,
    GuildVoiceMuteEvent,
    GuildVoiceDeafenEvent,
    GuildVoiceGuildMuteEvent,
    GuildVoiceGuildDeafenEvent,
    GuildVoiceSelfMuteEvent,
    GuildVoiceSelfDeafenEvent,
    GuildVoiceSuppressEvent,

    RoleCreateEvent,
    RoleDeleteEvent,

    RoleUpdateColorEvent,
    RoleUpdateHoistedEvent,
    RoleUpdateMentionableEvent,
    RoleUpdateNameEvent,
    RoleUpdatePermissionsEvent,
    RoleUpdatePositionEvent,

    EmoteAddedEvent,
    EmoteRemovedEvent,

    EmoteUpdateNameEvent,
    EmoteUpdateRolesEvent,

    HttpRequestEvent,

    GenericMessageEvent,
    GenericMessageReactionEvent,
    GenericGuildMessageEvent,
    GenericGuildMessageReactionEvent,
    GenericPrivateMessageEvent,
    GenericPrivateMessageReactionEvent,
    GenericUserEvent,
    GenericUserPresenceEvent,
    GenericSelfUpdateEvent,
    GenericStoreChannelEvent,
    GenericStoreChannelUpdateEvent,
    GenericTextChannelEvent,
    GenericTextChannelUpdateEvent,
    GenericVoiceChannelEvent,
    GenericVoiceChannelUpdateEvent,
    GenericCategoryEvent,
    GenericCategoryUpdateEvent,
    GenericGuildEvent,
    GenericGuildUpdateEvent,
    GenericGuildMemberEvent,
    GenericGuildMemberUpdateEvent,
    GenericGuildVoiceEvent,
    GenericRoleEvent,
    GenericRoleUpdateEvent,
    GenericEmoteEvent,
    GenericEmoteUpdateEvent,

    StatusUpdate,
    ResumedEvent
}